[project]
name = "schedule-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nam0vicH", email = "wot12re@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
schedule-bot = "schedule_bot:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
